### ISSUE TITLE
ValueError: None values not supported. 

### ISSUE THREAD

**Issue by thisisashukla** [hyperopt/hyperopt#364] opened 2018-02-06 08:59 UTC
I am trying to optimize a simple Autoencoder model. I am getting a ValueError. Any help would be great. Apologies if I am creating a redundant issue or if its a silly one.

# Code:
```python
def data():
    """
    Data providing function:

    This function is separated from create_model() so that hyperopt
    won't reload data for each evaluation run.
    """
    x_train=np.load('path-to-training-data')
    x_val=np.load('path-to-validation-data')
    x_test=np.load('path-to-testing-data')
    
    train=np.vstack((x_train,x_val))
    
    return (train, train), (x_test, x_test)

def create_model(train_data, optim=Adadelta(lr=0.001, rho=0.95,decay=0.0001)):
    
    # Writing the MODEL
    sample_size=32
    channels=220
    input_img = Input(shape=(sample_size, sample_size, channels))

    ## ENCODER
    x = Conv2D(110, (2, 2), input_shape=(sample_size, sample_size, channels), activation='relu', padding='same', data_format='channels_last')(input_img)
    x = Conv2D(55, (2, 2), activation='relu', padding='same', data_format='channels_last')(x)
    encoded = Conv2D(30, (2, 2), activation='relu', padding='same', data_format='channels_last')(x)
    
    ## DECODER
    x = Conv2D(30, (2, 2), activation='relu', padding='same', data_format='channels_last')(encoded)
    x = Conv2D(55, (2, 2), activation='relu', padding='same', data_format='channels_last')(x)
    x = Conv2D(110, (2, 2), activation='relu', padding='same', data_format='channels_last')(x)
    decoded = Conv2D(channels, (2, 2), activation='sigmoid', padding='same', data_format='channels_last')(x)
    
    ## Compiling Model
    autoencoder = Model(input_img, decoded)
    autoencoder.compile(optimizer=optim, loss='mean_squared_error',metrics=['accuracy'])

    return autoencoder

# Specify the optimization metrics
db_name="mongodb"
exp_name="myexp1"
objective = CompileFN(db_name, exp_name,
                      data_fn=data,
                      model_fn=create_model,
                      loss_metric="acc", # which metric to optimize for
                      loss_metric_mode="max",  # try to maximize the metric
                      valid_split=.2, # use 20% of the training data for the validation set
                      save_model='best', # checkpoint the best model
                      save_results=True, # save the results as .json (in addition to mongoDB)
                      save_dir="./saved_models/")  # place to store the models

# define the hyper-parameter ranges
# see https://github.com/hyperopt/hyperopt/wiki/FMin for more info
scope.define(SGD)
scope.define(Adadelta)
space = {
    "data": {},
    "model": {
        "optim":hp.choice("optimizer",[scope.SGD(lr=hp.loguniform("lr_sgd", np.log(1e-4), np.log(1e-2)), 
                                                 decay=hp.loguniform("decay_sgd", np.log(1e-4), np.log(1e-2)), 
                                                 momentum=hp.uniform("momentum", 0, 1), nesterov=hp.choice("nesterov", (True,False))),
                                       scope.Adadelta(lr=hp.loguniform("lr_ada", np.log(1e-4), np.log(1e-2)), 
                                                rho=hp.uniform("rho", 0, 1), epsilon=None,
                                                decay=hp.loguniform("decay_ada", np.log(1e-4), np.log(1e-2)))])
    },
    "fit": {
        "epochs": 20
    }
}

# test model training, on a small subset for one epoch
test_fn(objective, space)

# run hyper-parameter optimization sequentially (without any database)
trials = Trials()
best = fmin(objective, space, trials=trials, algo=tpe.suggest, max_evals=5)
```
# Stacktrace:
```
ValueError                                Traceback (most recent call last)
<ipython-input-8-072c98a7ea75> in <module>()
      1 # test model training, on a small subset for one epoch
----> 2 test_fn(objective, space)
      3 
      4 # run hyper-parameter optimization sequentially (without any database)
      5 trials = Trials()

G:\Programs\anaconda3\envs\py35\lib\site-packages\kopt-0.1.0-py3.5.egg\kopt\hyopt.py in test_fn(fn, hyper_params, n_train, save_model, tmp_dir, custom_objects)
     66 
     67     # correct execution
---> 68     res = fn(param)
     69     print("Returned value:")
     70     pprint.pprint(res)

G:\Programs\anaconda3\envs\py35\lib\site-packages\kopt-0.1.0-py3.5.egg\kopt\hyopt.py in __call__(self, param)
    630                                                            eval_best=self.save_model == "best",
    631                                                            add_eval_metrics=self.add_eval_metrics,
--> 632                                                            custom_objects=self.custom_objects)
    633             if self.save_model == "last":
    634                 model.save(model_path)

G:\Programs\anaconda3\envs\py35\lib\site-packages\kopt-0.1.0-py3.5.egg\kopt\hyopt.py in _train_and_eval_single(train, valid, model, batch_size, epochs, use_weight, callbacks, eval_best, add_eval_metrics, custom_objects)
    359               sample_weight=sample_weight,
    360               verbose=2,
--> 361               callbacks=[history] + callbacks)
    362 
    363     # get history

G:\Programs\anaconda3\envs\py35\lib\site-packages\keras\engine\training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, **kwargs)
   1411         else:
   1412             ins = x + y + sample_weights
-> 1413         self._make_train_function()
   1414         f = self.train_function
   1415 

G:\Programs\anaconda3\envs\py35\lib\site-packages\keras\engine\training.py in _make_train_function(self)
    935                 self._collected_trainable_weights,
    936                 self.constraints,
--> 937                 self.total_loss)
    938             updates = self.updates + training_updates
    939             # Gets loss and metrics. Updates weights at each call.

G:\Programs\anaconda3\envs\py35\lib\site-packages\keras\optimizers.py in get_updates(self, params, constraints, loss)
    351 
    352             # use the new accumulator and the *old* delta_accumulator
--> 353             update = g * K.sqrt(d_a + self.epsilon) / K.sqrt(new_a + self.epsilon)
    354 
    355             new_p = p - lr * update

G:\Programs\anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\variables.py in _run_op(a, *args)
    665     def _run_op(a, *args):
    666       # pylint: disable=protected-access
--> 667       return getattr(ops.Tensor, operator)(a._AsTensor(), *args)
    668     # Propagate __doc__ to wrapper
    669     try:

G:\Programs\anaconda3\envs\py35\lib\site-packages\tensorflow\python\ops\math_ops.py in binary_op_wrapper(x, y)
    818     with ops.name_scope(None, op_name, [x, y]) as name:
    819       if not isinstance(y, sparse_tensor.SparseTensor):
--> 820         y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
    821       return func(x, y, name=name)
    822 

G:\Programs\anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\ops.py in convert_to_tensor(value, dtype, name, preferred_dtype)
    637       name=name,
    638       preferred_dtype=preferred_dtype,
--> 639       as_ref=False)
    640 
    641 

G:\Programs\anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\ops.py in internal_convert_to_tensor(value, dtype, name, as_ref, preferred_dtype)
    702 
    703         if ret is None:
--> 704           ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    705 
    706         if ret is NotImplemented:

G:\Programs\anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\constant_op.py in _constant_tensor_conversion_function(v, dtype, name, as_ref)
    111                                          as_ref=False):
    112   _ = as_ref
--> 113   return constant(v, dtype=dtype, name=name)
    114 
    115 

G:\Programs\anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\constant_op.py in constant(value, dtype, shape, name, verify_shape)
    100   tensor_value = attr_value_pb2.AttrValue()
    101   tensor_value.tensor.CopyFrom(
--> 102       tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
    103   dtype_value = attr_value_pb2.AttrValue(type=tensor_value.tensor.dtype)
    104   const_tensor = g.create_op(

G:\Programs\anaconda3\envs\py35\lib\site-packages\tensorflow\python\framework\tensor_util.py in make_tensor_proto(values, dtype, shape, verify_shape)
    358   else:
    359     if values is None:
--> 360       raise ValueError("None values not supported.")
    361     # if dtype is provided, forces numpy array to be the type
    362     # provided if possible.

ValueError: None values not supported.
```

**Comment by michaelmior** [comment] 2023-06-18 16:06
I believe the issue is that you specified `epsilon=None` which is not a valid value for this parameter. I'm going to close this issue, but feel free to reopen if you're still having a problem.

**Closed by michaelmior** 2023-06-18 16:06 UTC
