### ISSUE TITLE
XGBoostError: value 108 for parameter colsample_by_tree exceed bound [0,1]

### ISSUE THREAD

**Issue by xywust2014** [hyperopt/hyperopt#584] opened 2019-12-06 14:07 UTC
Hi, 

I am tuning a xgboost classifier model with hyperopt. I encountered an error which shows: "XGBoostError: value 108 for parameter colsample_by_tree exceed bound [0,1]". But this value is clearly set between [0, 1]

**### Environment** 
Python 3.6, window 10. 

**Part of my test code**
 
```
def score(params):
    print("Training with params: ")
    print(params)
    num_round = int(params['n_estimators'])
    del params['n_estimators']
    cv_results = xgb.cv(params, dtrain, num_round, nfold = N_FOLDS, stratified = True, verbose_eval = True, metrics = 'auc', early_stopping_rounds = 200)
    best_score = np.max(cv_results['test-auc-mean'])
    print(np.round(best_score, 5))
    loss = 1 - best_score 
    return {'loss': loss, 'status':STATUS_OK}
 
 
SEED = 101 
def optimize(random_state = SEED):
     
    """
#     This is the optimization function that given a space of hyperparameters and a 
#     scoring function (score here), finds to best hyperparameters. 
#     To learn more about XGBoost parameters, head to this page: 
#     https://github.com/dmlc/xgboost/blob/master/doc/parameter.md
#     """
# =============================================================================
    space = {
            'n_estimators': hp.choice('n_estimators', [100,200,300, 400, 500]) , 
            'max_depth':hp.choice('max_depth', [2, 3, 6, 8, 10, 12, 14, 16]), 
            'min_child_weight':hp.choice('min_child_weight', list(np.linspace(0, 2000, 2001))), 
            'lambda':hp.choice('lambda', [1, 1.2, 1.5, 2]), 
            'grow_policy':'lossguide', 
            'learning_rate':hp.choice('learning_rate', [0.01, 0.1,0.15,0.2]), 
            'gamma':hp.choice('gamma', [1, 2, 2.5, 3, 4]), 
            'colsample_bytree':hp.choice('colsample_bytree', list(np.linspace(0.01, 1, 199))),
            'max_leaves': hp.choice('max_leaves', [0, 100, 200, 350, 550]), 
            'eval_metric':'auc', 
             'objective':'binary:logistic'
            }
    best = fmin(score, space, algo = tpe.suggest, max_evals = 5)
    return best 
 
best_hyperparams = optimize()

print("The best hyperparameters are: ", "\n")
print(best_hyperparams)
```

**### Error is shown as below** 

  File "C:\Users\e009029\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\e009029\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/e009029/Documents/GH/Model/ER.Events/v1.1.1/EAD_train_v1.1.1.py", line 266, in <module>
    model = xgb.train(param, dtrain, num_boost_round = 200, evals = evallist)

  File "C:\Users\e009029\AppData\Local\Continuum\anaconda3\lib\site-packages\xgboost\training.py", line 216, in train
    xgb_model=xgb_model, callbacks=callbacks)

  File "C:\Users\e009029\AppData\Local\Continuum\anaconda3\lib\site-packages\xgboost\training.py", line 74, in _train_internal
    bst.update(dtrain, i, obj)

  File "C:\Users\e009029\AppData\Local\Continuum\anaconda3\lib\site-packages\xgboost\core.py", line 1109, in update
    dtrain.handle))

  File "C:\Users\e009029\AppData\Local\Continuum\anaconda3\lib\site-packages\xgboost\core.py", line 176, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))

XGBoostError: value 108 for Parameter colsample_bytree exceed bound [0,1]

**Comment by bjkomer** [comment] 2019-12-06 19:04
This is a common problem people run into. The parameter values for `hp.choice` are stored as indices. You can use `space_eval` to convert the output from `fmin` to something your function will understand.

```python
from hyperopt import space_eval
# ...
params = space_eval(space, best)
```

From the change in #463 it is possible to get the output of `fmin` to be in the form you are expecting directly by setting the parameter `return_argmin=False` in `fmin`

duplicate of #412, #431, #511, #550 , #576

**Comment by bjkomer** [comment] 2019-12-06 19:15
Side note: you may want to use `hp.quniform` instead of `hp.choice` for many of your hyperparameters since `hp.choice` is meant for categorical values the search algorithm will not attempt to use any relation between nearby values.

**Closed** 2019-12-06 19:36 UTC
