### ISSUE TITLE
Problem with search space

### ISSUE THREAD

**Issue by blazejdolicki** [hyperopt/hyperopt#761] opened 2020-10-28 13:55 UTC
First of all, thank you for creating this library, I saw it a couple of days ago and seems really cool. Unfortunately, when trying it out I stumbled upon problems that I describe above.

My issue is that in the beginning, I used hp.choice() to give a finite number of options for my hyperparameters. But when I saw the parameters used, the values didn't coincide with the ones I specified in the search space.

This is my code
```
from hyperopt import fmin, hp, rand
from hyperopt import SparkTrials, STATUS_OK, Trials

current_hyperparams = ["oversample", "undersample", "max_bins", "feature_subset_strat", "max_depth", "subsampling_rate", "max_iter", "step_size", "min_instances_per_node"]
run = runs[0]

search_space = {
  'oversample': hp.choice('oversample', [1.0, 1.5, 2.0]),
  'undersample': hp.choice('undersample', [0.1, 0.15, 0.5]),
  'max_bins': hp.choice('max_bins', [15000]),
  'feature_subset_strat': hp.choice('feature_subset_strat', ["sqrt"]),
  'max_depth': hp.choice('max_depth', [5]),
  'subsampling_rate': hp.choice('subsampling_rate', [0.5]),
  'max_iter': hp.choice('max_iter', [5]),
  'step_size': hp.choice('step_size', [0.03]),
  'min_instances_per_node':hp.choice('min_instances_per_node', [40])
  
}

# Select a search algorithm for Hyperopt to use.
algo=rand.suggest  # random search

# We can distribute tuning across our Spark cluster
# by calling `fmin` with a `SparkTrials` instance.
# spark_trials = SparkTrials()
train = run[0]
test = run[1]
run_name = run[2]
serial_trials = Trials()

best_hyperparameters = fmin(
  fn=train_test_model,
  space=search_space,
  algo=algo,
  trials=serial_trials,
  max_evals=1) 
best_hyperparameters
```
Output:
```
Out[25]: {'feature_subset_strat': 0,
 'max_bins': 0,
 'max_depth': 0,
 'max_iter': 0,
 'min_instances_per_node': 0,
 'oversample': 2,
 'step_size': 0,
 'subsampling_rate': 0,
 'undersample': 1}
```

**Comment by bjkomer** [comment] 2020-10-28 15:18
Internally `hp.choice` only stores the indices of the values tried, not the values themselves, as search spaces can be arbitrarily nested using choice. The output can be converted back using the `space_eval` helper function, or by setting `return_argmin=False` in `fmin`. This issue does seem to come up a lot, so may be worth changing the default behaviour, though this may initially break other packages that depend on hyperopt.

Duplicate of #746

**Comment by blazejdolicki** [comment] 2020-10-29 18:53
Thanks for a swift response, I will try to make a pull request in the documentation soon.

**Closed** 2020-10-29 18:53 UTC
