### ISSUE TITLE
Test failures on master?

### ISSUE THREAD

**Issue by amueller** [hyperopt/hyperopt#315] opened 2017-08-02 18:49 UTC
```
======================================================================
ERROR: test_basic (hyperopt.tests.test_pchoice.TestPChoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andy/checkout/hyperopt/hyperopt/tests/test_pchoice.py", line 21, in test_basic
    nesto = hyperopt.pyll.stochastic.sample(space, rng=rng)
  File "/home/andy/checkout/hyperopt/hyperopt/pyll/stochastic.py", line 196, in sample
    return rec_eval(foo, **kwargs)
  File "/home/andy/checkout/hyperopt/hyperopt/pyll/base.py", line 874, in rec_eval
    rval_var = node.pos_args[switch_i + 1]
TypeError: only integer scalar arrays can be converted to a scalar index

======================================================================
ERROR: test_basic2 (hyperopt.tests.test_pchoice.TestPChoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andy/checkout/hyperopt/hyperopt/tests/test_pchoice.py", line 45, in test_basic2
    nesto = hyperopt.pyll.stochastic.sample(space, rng=rng)
  File "/home/andy/checkout/hyperopt/hyperopt/pyll/stochastic.py", line 196, in sample
    return rec_eval(foo, **kwargs)
  File "/home/andy/checkout/hyperopt/hyperopt/pyll/base.py", line 874, in rec_eval
    rval_var = node.pos_args[switch_i + 1]
TypeError: only integer scalar arrays can be converted to a scalar index

======================================================================
ERROR: test_basic3 (hyperopt.tests.test_pchoice.TestPChoice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andy/checkout/hyperopt/hyperopt/tests/test_pchoice.py", line 68, in test_basic3
    nesto = hyperopt.pyll.stochastic.sample(space, rng=rng)
  File "/home/andy/checkout/hyperopt/hyperopt/pyll/stochastic.py", line 196, in sample
    return rec_eval(foo, **kwargs)
  File "/home/andy/checkout/hyperopt/hyperopt/pyll/base.py", line 874, in rec_eval
    rval_var = node.pos_args[switch_i + 1]
TypeError: only integer scalar arrays can be converted to a scalar index

======================================================================
ERROR: test_mu_is_used_correctly (hyperopt.tests.test_tpe.TestGMM1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andy/checkout/hyperopt/hyperopt/tests/test_tpe.py", line 79, in test_mu_is_used_correctly
    GMM1([1], [10.0], [0.0000001], rng=self.rng))
  File "/home/andy/checkout/hyperopt/hyperopt/tpe.py", line 79, in GMM1
    active = np.argmax(rng.multinomial(1, weights, (n_samples,)), axis=1)
  File "mtrand.pyx", line 4621, in mtrand.RandomState.multinomial (numpy/random/mtrand/mtrand.c:37893)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

======================================================================
FAIL: test_q1lognormal (hyperopt.tests.test_anneal.TestItAtLeastSortOfWorks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/andy/checkout/hyperopt/hyperopt/tests/test_domains.py", line 249, in test_q1lognormal
    self.work()
  File "/home/andy/checkout/hyperopt/hyperopt/tests/test_anneal.py", line 114, in work
    assert min(trials.losses()) < thresh
AssertionError

----------------------------------------------------------------------
Ran 191 tests in 51.085s

FAILED (SKIP=2, errors=4, failures=1)

```

**Comment by nouiz** [comment] 2017-08-03 12:36
I think the problem is that your NumPy is to recent for hyperopt.

Newer numpy always need fixes in Theano and we for sick type of errors.

Le mer. 2 août 2017 14:49, Andreas Mueller <notifications@github.com> a
écrit :

**Comment by amueller** [comment] 2017-08-03 13:03
Thanks for your reply. I'm using numpy ``1.11.1``.
Sorry, the second sentence didn't parse.

The first three errors are because ``switch_i`` is a ``(1, )`` array, but I didn't know where a good place would be for the conversion - I could do it where the error happens, but that might hide some issue further up, as I'm not familiar with the code. The 4th seems like a simple casting issues, but the last one seems like an optimization issue, so I have no ideas.

**Comment by nouiz** [comment] 2017-08-10 17:30
I'm not able to help more as I don't use hyperopt. I was just mantioning
something that could help. Using older numpy could fix some of those
problems, as hyperopt was made with other numpy then 1.11. I can't help
more.

**Comment by aldanor** [comment] 2017-12-26 20:46
Any ideas on this? The first three seem to be a lack of a simple conversion (somewhere appropriate) as @amueller mentioned, but what about the 4th?

(On a side note, is hyperopt currently maintained by anyone?)

**Comment by michaelmior** [comment] 2023-06-18 16:11
Closing since this refers to an outdated version of hyperopt. Feel free to reopen if you're still having any issues.

**Closed by michaelmior** 2023-06-18 16:11 UTC
